resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      ref: refs/heads/main
      endpoint: github

jobs:
  - template: nsls2-collection-2022-1.0-py39.yml@templates
    job: run_profile_collection_2022_1_0_py39_mxtools_main
    parameters:
      beamline_acronym: FMX
      mxtools_branch: main
  - template: nsls2-collection-2022-1.0-py39.yml@templates
    job: run_profile_collection_2022_1_0_py39_mxtools_pr
    parameters:
      beamline_acronym: FMX
      mxtools_branch: fmx-profile_collection-classes
