resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      ref: refs/heads/test-unique-job-names
      endpoint: github

jobs:
  - template: nsls2-collection-2022-1.0-py39.yml@templates
    parameters:
      beamline_acronym: FMX
    env:
      MXTOOLS_BRANCH: main
  - template: nsls2-collection-2022-1.0-py39.yml@templates
    parameters:
      beamline_acronym: FMX
    env:
      MXTOOLS_BRANCH: fmx-profile_collection-classes
