resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      ref: refs/heads/main
      endpoint: github

jobs:
  - template: nsls2-collection-2021-2.2.yml@templates
    parameters:
      beamline_acronym: FMX
  - template: nsls2-collection-2022-1.0-py39.yml@templates
    parameters:
      beamline_acronym: FMX
